### ISSUE TITLE
Fix Fork Relationship of Repository

### ISSUE THREAD

**Issue by vvolkl** [key4hep/k4-spack#18]
This is not really a fork of hsf/hep-spack anymore, but k4-spack being a fork tends to mess up pull requests. I think there is not other way but  to delete and recreate this repository in order to get rid of the fork information.

**Comment by joequant** [comment]
I think you can ask the github admins to remove the fork information.

https://www.quora.com/Git-revision-control-How-can-one-detach-a-forked-project-in-GitHub

**Comment by vvolkl** [comment]
Thanks for the suggestion, github support managed to do this quite quickly.
