### ISSUE TITLE
GNU compiler issue when sourcing edm4hep

### ISSUE THREAD

**Issue by clementhelsens** [key4hep/k4-spack#34]
When sourcing EDM4Hep

source /cvmfs/sw.hsf.org/spackages/edm4hep.sh

The GNU compilers stays default. So on lxplus we are left using a very old version 4.8.5.

The setup script needs some adjustments.

**Comment by vvolkl** [comment]
Should be fixed in the script on cvmfs. I'll update documentation with the details of how it is generated.

**Comment by vvolkl** [comment]
Fixed.
