### ISSUE TITLE
fcalcclusterer fails to compile with stdc++-17

### ISSUE THREAD

**Issue by joequant** [key4hep/k4-spack#43]
fcalcclusterer fails to compile when set to stdc++-17 because std::random_shuffle has been removed

/tmp/user/spack-stage/spack-stage-fcalclusterer-1.0.1-6uszwdiiq25ca4yyeofqasn6mufg6tmb/spack-src/source/BeamCalReco/src/BeamCalBkgPregen.cpp:70:8: error: no member named 'random_shuffle' in namespace 'std' [clang-diagnostic-error]
  std::random_shuffle(bg_files.begin(), bg_files.end());
       ^
1 error generated.
Error while processing /tmp/user/spack-stage/spack-stage-fcalclusterer-1.0.1-6uszwdiiq25ca4yyeofqasn6mufg6tmb/spack-src/source/BeamCalReco/src/BeamCalBkgPregen.cpp.
Found compiler error(s).
:

**Comment by joequant** [comment]
It appears that Andre has already fixed this issue in master, so I think the real fix is to have him release another version with the bug fix.

**Comment by andresailer** [comment]
I made FCalClusterer 1.0.2

**Comment by andresailer** [comment]
Solved in #53
