### ISSUE TITLE
Always enable lcio variant for DD4hep

### ISSUE THREAD

**Issue by andresailer** [key4hep/k4-spack#56]
For the key4hep-stack the dd4hep +lcio variant is enabled (#55). But if one builds another package, .e.g. MarlinTrkProcessors, this doesn't necessarily pick up the variant, which might then trigger an unnecessary re-build of dd4hep?

**Comment by vvolkl** [comment]
If a `packages.yaml` is used, this is easily fixed (see my PR). Another reason why this is probably the better mechanism for "soft" dependencies.
