### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by joequant** [key4hep/k4-spack#63]
Looks like the Pythia API changed

distcc[35634] Warning: failed to distribute /tmp/user/spack-stage/spack-stage-edm4hep-0.2.0-pyko3gyskg7y4vyrjonx2xrqhx76aird/spack-src/plugins/delphes/DelphesPythia8_EDM4HEP.cpp to 172.17.0.1,lzo, running locally instead
In file included from /tmp/user/spack-stage/spack-stage-edm4hep-0.2.0-pyko3gyskg7y4vyrjonx2xrqhx76aird/spack-src/plugins/delphes/DelphesPythia8_EDM4HEP.cpp:3:
/tmp/user/spack-stage/spack-stage-edm4hep-0.2.0-pyko3gyskg7y4vyrjonx2xrqhx76aird/spack-src/plugins/delphes/DelphesPythia8Reader.h: In member function 'virtual bool DelphesPythia8Reader::init(Delphes*, int, char**, std::string&)':
/tmp/user/spack-stage/spack-stage-edm4hep-0.2.0-pyko3gyskg7y4vyrjonx2xrqhx76aird/spack-src/plugins/delphes/DelphesPythia8Reader.h:212:26: error: 'class Pythia8::CombineMatchingInput' has no member named 'getHook'; did you mean 'setHook'?
  212 |     matching = combined->getHook(*pythia);
      |                          ^~~~~~~
      |                          setHook
/tmp/user/spack-stage/spack-stage-edm4hep-0.2.0-pyko3gyskg7y4vyrjonx2xrqhx76aird/spack-src/plugins/delphes/DelphesPythia8Reader.h:217:29: error: cannot convert 'Pythia8::UserHooks*' to 'Pythia8::UserHooksPtr' {aka 'std::shared_ptr<Pythia8::UserHooks>'}
  217 |     pythia->setUserHooksPtr(matching);
      |                             ^~~~~~~~
      |                             |
      |                             Pythia8::UserHooks*
In file included from /tmp/user/spack-stage/spack-stage-edm4hep-0.2.0-pyko3gyskg7y4vyrjonx2xrqhx76aird/spack-src/plugins/delphes/DelphesPythia8Reader.h:22,
                 from /tmp/user/spack-stage/spack-stage-edm4hep-0.2.0-pyko3gyskg7y4vyrjonx2xrqhx76aird/spack-src/plugins/delphes/DelphesPythia8_EDM4HEP.cpp:3:
/opt/spack/linux-mageia8-skylake/gcc-10.2.0/pythia8-8303-hhdw6phfk25dyvxzxrw32gutitzaivv4/include/Pythia8/Pythia.h:136:37: note:   initializing argument 1 of 'bool Pythia8::Pythia::setUserHooksPtr(Pythia8::UserHooksPtr)'
  136 |   bool setUserHooksPtr(UserHooksPtr userHooksPtrIn) {
      |                        ~~~~~~~~~~~~~^~~~~~~~~~~~~~
cd /tmp/user/spack-stage/spack-stage-edm4hep-0.2.0-pyko3gyskg7y4vyrjonx2xrqhx76aird/spack-build && /opt/spack/linux-mageia8-skylake/gcc-10.2.0/cmake-3.18.2-2elvn6eghzdxgcinedwbqumkvhl6dw5n/bin/cmake -E cmake_depends "Unix Makefiles" /tmp/user/spack-stage/spack-stage-edm4hep-0.2.0-pyko3gyskg7y4vyrjonx2xrqhx76aird/spack-src /tmp/user/spack-stage/spack-stage-edm4hep-0.2.0-pyko3gyskg7y4vyrjonx2xrqhx76aird/spack-src/edm4hep /tmp/user/spack-stage/spack-stage-edm4hep-0.2.0-pyko3gyskg7y4vyrjonx2xrqhx76aird/spack-build /tmp/user/spack-stage/spack-stage-edm4hep-0.2.0-pyko3gyskg7y4vyrjonx2xrqhx76aird/spack-build/edm4hep /tmp/user/spack-stage/spack-stage-edm4hep-0.2.0-pyko3gyskg7y4vyrjonx2xrqhx76aird/spack-build/edm4hep/CMakeFiles/edm4hepDict.dir/DependInfo.cmake --color=
Scanning dependencies of target edm4hepDict
make[2]: Leaving directory '/tmp/user/spack-stage/

**Comment by vvolkl** [comment]
Indeed, and Frank already fixed it in https://github.com/key4hep/EDM4hep/pull/79. But the edm4hep version 0.2.0 needs an additionaly dependency.
