### ISSUE TITLE
Disable adding the latest commit as version if GITHUB_USER or GITHUB_TOKEN are not set?

### ISSUE THREAD

**Issue by tmadlener** [key4hep/k4-spack#69]
In #61 the possibility to add the latest commit as version was added. If `GITHUB_USER` and `GITHUB_TOKEN` are not set this leads to a lot of warnings of the kind

```
Warning: could not fetch latest commit for edm4hep
Warning: could not fetch latest commit for k4fwcore
# similar for all packages
```

Since this is arguably an "expert" feature, maybe we should consider that we omit these checks if the two environment variables are not set, as querying the github api for several packages can lead to significantly longer times to concretize a spec that uses `k4_add_latest_commit_as_[version|dependency]`. Additionally, the emitted warning messages might be confusing for users who just want the latest stable version of everything.

**Comment by vvolkl** [comment]
Fine for me.
