### ISSUE TITLE
Getting invalid checksum in downloading k4fwcore

### ISSUE THREAD

**Issue by joequant** [key4hep/k4-spack#90]
==> Installing k4fwcore
==> No binary for k4fwcore found: installing from source
==> Fetching https://github.com/key4hep/K4FWCore/archive/v00-01-01.tar.gz
#=#=#                                                                         
######################################################################## 100.0%##O#-#                                                                        
##=O#- #                                                                      
#-#O=#  #                                                                     
==> Error: ChecksumError: sha256 checksum failed for /tmp/user/spack-stage/spack-stage-k4fwcore-0.1.1-atvoiqohdaxte7ygceue4pix3drrdbb7/v00-01-01.tar.gz
    Expected 3a8b8267dc16691dbfef10d8faa8c0ec84ebf2d243069401db07a6706125d3a4 but got 9c4e4b487f7d9c982547c13570345399505e763fb369b76ceadb35c1d52bf6aa
/usr/lib/spack/spack/package.py:1274, in do_fetch:
       1271        self.stage.fetch(mirror_only, err_msg=err_msg)
       1272        self._fetch_time = time.time() - start_time
       1273
  >>   1274        if checksum and self.version in self.versions:
       1275            self.stage.check()
       1276
       1277        self.stage.cache_local()

**Comment by tmadlener** [comment]
Looks like the checksum of the tarball that we get from github has changed. At least when I get it directly and calculate the `sha256sum` I get the same as you and not the expected one.

I am not entirely sure what has changed though. Was there another tag with the same version?

**Comment by vvolkl** [comment]
Actually I just recently changed the repository name, `K4FWCore` -> `k4FWCore` as per the discussion in the meeting. I didn't expect it to change any checksums, but it could very well have done. In that case we just need to regenerate the checksums.
