### ISSUE TITLE
need to add +llvm to work around mesa

### ISSUE THREAD

**Issue by joequant** [key4hep/k4-spack#94]
Need to add to packages.yaml
```
mesa:
  variants: +llvm
```

To avoid following error

```
==> mesa: Executing phase: 'meson'
==> Error: NameError: name 'SpecError' is not defined
/var/spack/repos/builtin/packages/mesa/package.py:158, in meson_args:
        155
        156        if args_swr_arches:
        157            if '+llvm' not in spec:
  >>    158                raise SpecError('Variant swr requires +llvm')
        159            args_gallium_drivers.append('swr')
        160            args.append('-Dswr-arches=' + ','.join(args_swr_arches))
        161
See build log for details:
  /tmp/user/spack-stage/spack-stage-mesa-20.2.1-4kkkaud5rhdzzo3v7y72mk2ymxhrmuly/spack-build-out.txt
```

**Comment by vvolkl** [comment]
Hi @joequant,

good catch! I'd try to avoid building llvm though, since it takes a lot of compilation time and disk space, and it is not clear if it is needed as part of the stack (root ships its own builtin llvm). Instead can you try `~llvm+swr=none`  as variants for mesa?

**Comment by joequant** [comment]
Trying turn off swr but not working.

spack/spack#19674

**Comment by joequant** [comment]
Also building llvm causes a ton of problems.  Will try to avoid it.

**Comment by vvolkl** [comment]
> Trying turn off swr but not working.
> 
> [spack/spack#19674](https://github.com/spack/spack/issues/19674)

Strange, this is working for me. I guess you should use the HEAD of the spack develop branch for this issue, since `mesa` was just changed recently, can you try that? But also this seems not connected to mesa, looks more like your spack cannot parse a simple spec.

**Comment by joequant** [comment]
This seems to work...

  mesa:
    variants: -llvm swr=none
