### ISSUE TITLE
Add common python tools

### ISSUE THREAD

**Issue by clementhelsens** [key4hep/k4-spack#96]
Those python modules are really useful for user analyses. I would recommend we had them to the stack when possible.

uproot4
awkward1
matplotlib
particle
tensorflow
zfit

**Comment by vvolkl** [comment]
I think the best thing is to add fccanalyses to spack, and add those as dependencies.

**Comment by vvolkl** [comment]
I'm adding everything except tensorflow and zfit right now, as tensorflow would trigger a complete rebuild due to the dependency on numpy =< 1.18 and zfit is not yet in spack.

**Comment by clementhelsens** [comment]
Thanks @vvolkl , FYI, after struggling with pip and versions of the packages, I have a stable recipe to properly install those packages locally for FCCAnalyses. So nothing really urgent to get them to the full stack
